### ISSUE TITLE
Changes to dieharder-rgb git?

### ISSUE THREAD

**Issue by mbroz** [eddelbuettel/dieharder#17]
Hi,
this is more question than an issue...

I tried to follow history of tests added/changed in Dieharder and found these commits in dieharder-rgb that are not part of this repo (commit list is not complete, just examples):

- Updated Fill Tree 2 target...
https://github.com/eddelbuettel/dieharder-rgb/commit/67c2cb9a468c73014886f20c22af12c5162aab9c

- Added OPSO2 test
https://github.com/eddelbuettel/dieharder-rgb/commit/db68bb7db56dac25a12e287c41fe80a3f7c00a5e

- Added Birthday Spacing test variant
https://github.com/eddelbuettel/dieharder-rgb/commit/afee5533ee434cf9ba12f22735d8bcfd4adb3dfd

What's the story behind these changes? Any reason is is not part of current  (this) Dieharder repository? Does the repo just diverged?

Thanks!

**Comment by eddelbuettel** [comment]
Yes I think it just diverged.  I became care-taker via either/both my Debian packaging of Diharder (the binary and library) and/or my R package RDieHarder (wrapping the library) as Robert is mostly silent these years.

**Comment by eddelbuettel** [comment]
Those three commits are from 2016 and 2013 (!!).  Do you want to try to 'port them' here?

**Comment by mbroz** [comment]
> Those three commits are from 2016 and 2013 (!!). Do you want to try to 'port them' here?

If it makes sense, I can try to do port changes here for libdieharder/dieharder code (rgb repo contains a lot more stuff that does not apply here like docs). There should not be many patches (well, I hope :-)

**Comment by eddelbuettel** [comment]
Yes they should be reasonably local.  The code has not changed much, we did make changes to accomodate ODR and things the compiler is pickier about making the diffs a little 'dirty'. But with some calm patience it should be doable.
